---
title: "Stat 1 R Code - Week 13"
author: "SMU"
date: "4/21/2022"
output: html_document
---

# Cleaning the global environment
```{r}
rm(list = ls())
```

```{r include = FALSE}
library(tidyverse)
library(ggplot2)
library(scales)
library(pwr)
library(agricolae)
library(huxtable)
library(lawstat)
library(lsmeans)
library(nCDunnett)
library(dplyr)
library(WDI)
library(investr)
library(multcomp)
library(pairwiseCI)
library(DescTools)
library(GGally)
```

# Tuna data
```{r}
Database = read.csv("D:/SMU/Ph.D./Data Science/Statistical Foundation for Data Science/Assignment/Unit 13/Tuna.csv")
```

```{r}
Database %>% ggplot(aes(Age, Length)) + geom_point() + geom_smooth(method = "lm")+ ggtitle("Length versus Age")

Database %>% ggplot(aes((Age + I(Age^2)), Length)) + geom_point() + geom_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1)+ ggtitle("Length versus Age and Age^2")
```


```{r}
fit = lm(Length ~ Age + I(Age^2), data = Database)
summary(fit)
plot(fit)
```
# Echolocation data
```{r}
Database = read.csv("D:/SMU/Ph.D./Data Science/Statistical Foundation for Data Science/Assignment/Unit 13/Echolocation.csv")
```

```{r}
ggpairs(Database[,c(1,3)], mapping=ggplot2::aes(color = Database$Type) )
```


```{r}
Database %>% ggplot(aes(Mass, Energy, color = Type, shape= Type)) + geom_point() + geom_smooth(method = "lm")+ ggtitle("Energy Force versus Mass")

Database %>% ggplot(aes(Mass, Energy, color = Type, shape= Type)) + geom_point() + ggtitle("Energy Force versus Mass")
```
# Log transformation
```{r}
Databasescale <- as.data.frame(sapply(Database[,c(1,3)], function(x) (log(x))))
ggpairs(Databasescale[,c(1,2)], mapping=ggplot2::aes(color = Database$Type) )
```
```{r}
Database$Mass <- log(Database$Mass)
Database$Energy <- log(Database$Energy)
fit = lm(Energy ~ Mass + Type, data = Database)
summary(fit)
plot(fit)
```

```{r}
n = 5
sigma = 5
TheData = c()
TheCurrentData = c()
TheTrueMean = c()

for (i in 1:n)
{
  x = i
  y = rnorm(1, 5*x + 3, sigma)
  TheTrueMean = 5*x + 3
  TheCurrentData = cbind(x,y,TheTrueMean)
  TheData = rbind(TheData, TheCurrentData)
}

TheData = data.frame(TheData)
TheData

plot(TheData$x, TheData$y, xlab = "x", ylab = "y", xlim = c(0,n), ylim = c(0,80))
lines(TheData$x, TheData$TheTrueMean, lty = 1)

fitdeg1 = lm(y~x, data = TheData)
RegLineDeg1 = predict(fitdeg1)
lines(TheData$x, RegLineDeg1, lty = 1, col = "blue")

fitDeg10 = lm(y ~ x + I(x^2) + I(x^3) + I(x^4) + I(x^5) + I(x^6) + I(x^7) + I(x^8) + I(x^9) + I(x^10), data = TheData  )
RegLineDeg10 = predict(fitDeg10)
summary(fitDeg10)

lines(TheData$x, RegLineDeg10, lty = 1, col = "red")
```

